[project]
name = "pysockets"
version = "0.1.0"
description = "Toy project for understanding how sockets work written in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymongo>=4.13.0",
    "typer>=0.15.4",
]
